# Generated by Django 4.1.1 on 2022-09-22 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(db_index=True, max_length=100, verbose_name='имя категории')),
                ('category_slug', models.SlugField(max_length=100, unique=True, verbose_name='url категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('category_name',),
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(error_messages='такой email уже зарегистрирован', max_length=254, primary_key=True, serialize=False, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('adress', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('code', models.CharField(db_index=True, error_messages='не уникален, измените', max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Артикул')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Краткое описание')),
                ('content', models.TextField(max_length=500, verbose_name='Описание')),
                ('droduct_slug', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='url товара')),
                ('image', models.ImageField(default='static\\main_app\\img\\image_not_yet_uploaded_by_unitedworldmedia_de1noau-fullview.png', upload_to='media/uploads', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена')),
                ('count', models.PositiveIntegerField(verbose_name='Остатки')),
                ('isActive', models.BooleanField(default=True, verbose_name='Наличие')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main_app.category')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(error_messages='такой номер уже есть', max_length=20, unique=True, verbose_name='Номер заказа')),
                ('order_time', models.DateTimeField()),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.clients')),
                ('ordered_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.products')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
