# Generated by Django 4.1.1 on 2022-09-22 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='droduct_slug',
            new_name='product_slug',
        ),
    ]
