# Generated by Django 4.1.1 on 2022-09-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_droduct_slug_products_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='id',
            field=models.BigAutoField(auto_created=True, default='1', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='code',
            field=models.CharField(db_index=True, error_messages='не уникален, измените', max_length=50, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='products',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='products',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterIndexTogether(
            name='products',
            index_together={('id', 'product_slug')},
        ),
    ]
