# Generated by Django 4.1.1 on 2022-09-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_products_id_alter_products_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='count',
            field=models.PositiveIntegerField(blank=True, default='0', verbose_name='Остатки'),
        ),
    ]
