# Generated by Django 4.1.1 on 2022-09-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_products_count'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='products',
            index_together=set(),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_slug',
            field=models.CharField(max_length=100, unique=True, verbose_name='url товара'),
        ),
    ]
