# Generated by Django 4.1.1 on 2022-09-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_products_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_slug',
            field=models.CharField(max_length=100, verbose_name='url товара'),
        ),
    ]
