# Generated by Django 4.1.1 on 2022-09-26 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_products_product_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('title',), 'permissions': (('add_produt', 'add_product'),), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
